/**
 * Triggers a browser download of generated bytes or text straight to the browser's download
 * folder, with no dialog -- the fallback `saveFileAs` (below) uses whenever the OS's own Save
 * dialog is not available. A `Blob` plus a momentary, invisible `<a download>` click, the
 * standard DOM idiom for saving generated bytes without a server round trip.
 */
export function downloadFile(filename, data, mimeType = 'application/octet-stream') {
  const blob = data instanceof Blob ? data : new Blob([data], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');

  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

/**
 * Saves generated bytes or text through the browser's own, native "Save As" dialog when it is
 * available (`window.showSaveFilePicker`, the File System Access API) -- the user picks the
 * folder and file name, and confirms or changes the file's type via the dialog's own "Save as
 * type" control, the way every desktop app's Save As already works, rather than the file
 * silently landing in the download folder under a name this page chose. `extensions` (e.g.
 * `['.gem']`) and `description` (e.g. `'GemCad design'`) become that one entry in the dialog's
 * type list; the browser adds its own "All Files" alternative alongside it.
 *
 * Falls back to `downloadFile` -- unchanged, no dialog -- whenever the picker cannot be used:
 * neither Firefox nor Safari implements it at all, it requires a secure context this project
 * cannot guarantee for a page opened directly from `file://` (this app's primary way of
 * running the built page -- see kb/page-and-controls.md), and it can throw for other reasons
 * (a filesystem or permission error). The one case that must NOT fall back is the user
 * cancelling the dialog (`AbortError`): nothing was meant to be saved, so this returns quietly
 * rather than saving anyway or reporting an error for a deliberate Cancel.
 */
export async function saveFileAs(suggestedName, data, { description, mimeType = 'application/octet-stream', extensions = [] } = {}) {
  if (typeof window.showSaveFilePicker === 'function') {
    try {
      const handle = await window.showSaveFilePicker({
        suggestedName,
        types: extensions.length > 0
          ? [{ description, accept: { [mimeType]: extensions } }]
          : undefined,
      });
      const writable = await handle.createWritable();

      await writable.write(data instanceof Blob ? data : new Blob([data], { type: mimeType }));
      await writable.close();
      return;
    } catch (cause) {
      if (cause?.name === 'AbortError') {
        return;
      }
      // Any other failure (unsupported context, permission, filesystem) falls through to the
      // plain download below rather than losing the export the user asked for.
    }
  }

  downloadFile(suggestedName, data, mimeType);
}
